# Generated by Django 4.2 on 2024-05-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categories', 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'default_related_name': 'skills', 'verbose_name': 'навык', 'verbose_name_plural': 'Навыки'},
        ),
    ]
